[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
rocket = { version = "0.5.0-rc.2", features = ["secrets", "tls", "json", "msgpack"] }
serde_json = "1.0.91"
deadpool-postgres = "0.10.3"
tokio-postgres = "0.7.7"
postgres-types = { version = "*", features = ["derive"] }
nanoid = "0.4.0"
dotenv = "0.15.0"
